### ISSUE TITLE
Consider writing yaml recipes

### ISSUE THREAD

**Issue by probonopd** [brotenet/AppImageTemplates#1]
Hi, great work. Maybe you'd like to check yaml recipes:
https://github.com/probonopd/AppImages/tree/master/recipes/meta

Here is one for a Java app:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/MediathekView.yml

This is the script that runs them:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/Recipe

**Comment by brotenet** [comment]
Thanks @probonopd for the links.

At this point I'm avoiding yaml because I'm thinking on building an app for it (as an Eclipse plugin and as standalone) and I want to have a manual process but with as few steps as possible.

**Comment by probonopd** [comment]
>  I want to have a manual process but with as few steps as possible

Wouldn't that be a good argument __for__ using the yaml?
