### ISSUE TITLE
Fail to run due to java not found

### ISSUE THREAD

**Issue by probonopd** [brotenet/AppImageTemplates#2]
On ubuntu-16.04-desktop-amd64.iso:

```
$ '/home/me/Downloads/NextReportsDesigner.AppImage' 
3102
/tmp/.mount_yHbiUP/usr/bin/run: line 12: java: command not found
```

Same for jNetMap:

```
$ '/home/me/Downloads/jNetMap.AppImage' 
3102
/tmp/.mount_oCgUpb/usr/bin/run: line 12: java: command not found
```
And RestClient:
```
$ '/home/me/Downloads/RestClient.AppImage' 
3102
/tmp/.mount_7xM3b1/usr/bin/run: line 12: java: command not found
```

And KeystoreExplorer:
```
$ '/home/me/Downloads/KeystoreExplorer.AppImage' 
3102
/tmp/.mount_gxcHqE/usr/bin/run: line 12: java: command not found
```

Please bundle JRE properly. AppImages must contain everything that cannot reasonably expected to be part of every target system.

**dBeaver, in contrast, is working.**

**Comment by brotenet** [comment]
I have updated the run files and made some changes on the directory structure.
Done also some tests under a Ubuntu 16.04 VM and they seem to be working OK.
I'll be testing also with a Korora VM and an Antegros VM in a while before I close this issue.

Can you check again if they work also on your side?

**Comment by probonopd** [comment]
Please put the download link in the README.md ;-)

**Comment by probonopd** [comment]
Working for me now, thanks!

**Comment by brotenet** [comment]
added the link to Bintray
