### ISSUE TITLE
AppImage files should follow naming guidelines

### ISSUE THREAD

**Issue by probonopd** [brotenet/AppImageTemplates#3]
Although not a strict requirement, it is best practice to follow naming guidelines for AppImage files:
`AppName-X.X.X.glibc2.XX-x86_64.AppImage`. The glibc part shows which glibc is the oldest one the AppImage can still run on.

**Comment by brotenet** [comment]
I will fix the namings when the tests in Korora and Antegros are done and the change the 'build' script to do as such

**Comment by probonopd** [comment]
appimagetool can do that for you automatically, too ;.)

**Comment by brotenet** [comment]
modified packagscripts

**Comment by brotenet** [comment]
added version/naming functionality in package_<app name>.sh files

**Comment by probonopd** [comment]
Thanks
