### ISSUE TITLE
Please provide zsync files and update information for AppImageUpdate

### ISSUE THREAD

**Issue by probonopd** [brotenet/AppImageTemplates#4]
AppImages should contain update information for [AppImageUpdate](https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/README.md), and there should be zsync files.

[appimagetool](https://github.com/probonopd/appimagetool) can do that for you. See the options
```
  -u, --updateinformation     Embed update information STRING; if zsyncmake is installed, generate zsync file
  --bintray-user              Bintray user name
  --bintray-repo              Bintray repository
```

This allows for neat tricks like [this](https://www.youtube.com/watch?v=FqVAtHdK1N0).

**Comment by brotenet** [comment]
I will need to do some reading over this because I'm still a newbie with AppImage...

**Comment by brotenet** [comment]
@probonopd 

Im trying to generate .zsync files for an appimage on BinTray as below: 
`zsyncmake -u https://bintray.com/brotenet/AppImages/download_file?file_path=KeystoreExplorer.AppImage`
..but it takes forever to make them.

s there any way I can create a .zsync file locally (on my PC) that would point to the AppImage on BinTray?

**Comment by probonopd** [comment]
You don't generate zsync files for AppImages that are already on a server. You always create the zsync files locally on your machine for an AppImage that is on your machine, and then you upload both, the AppImage and the zsync file, to Bintray or a HTTP server.

Let's say you have a directory `./MyApp`, and you have a Bintray account named `brotenet` with a Bintray repository named `AppImages`. Then you would run:

`./appimagetool ./MyApp -u --bintray-user=brotenet --bintray-repo=AppImages`.
You will get an AppImage and a sync file, which you both would need to upload to the AppImages repository of user brotenet on Bintray.

**Comment by brotenet** [comment]
@probonopd 
but when I run it as such it just hangs. 
![selection_004](https://cloud.githubusercontent.com/assets/4510965/19604974/5f1e1082-97c0-11e6-9f0b-83d7499337b4.png)

that's why I was trying directly with zsync

**Comment by probonopd** [comment]
Can you please give step-by-step instructions how to reproduce this, e.g., which repository to check out and what to do exactly.

**Comment by brotenet** [comment]
Now that the _appimagetool_ is fixed (https://github.com/probonopd/AppImageKit/issues/264) I've tried again with the Bintray info arguments, as below:
`./appimagetool KeystoreExplorer -u --bintray-user=brotenet --bintray-repo=AppImages`
but I get the following:
`The provided updateinformation is not in a recognized format`
![selection_008](https://cloud.githubusercontent.com/assets/4510965/19628215/4fa8fc6e-9961-11e6-8a6e-8bbc8050bc20.png)

**Comment by probonopd** [comment]
Oops. Let me look into it.

**Comment by probonopd** [comment]
Ah, right, `-u` is for the case when you want to provide your own updateinformation string. Call it like `./appimagetool KeystoreExplorer -u --bintray-user=brotenet --bintray-repo=AppImages` and it should work, even printing out `bintray-zsync|brotenet|AppImages|...|...` toward the end.

**Comment by brotenet** [comment]
you meant to say that I should call it as:
`./appimagetool KeystoreExplorer --bintray-user=brotenet --bintray-repo=AppImages`
without the `-u`

Thanks @probonopd it works great :+1: :+1: :+1:
